@auth.jwt.non_refresh_token_HostAddress = https://localhost:7165

Post {{auth.jwt.non_refresh_token_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "bishalgc@gmail.com",
  "password": "asjhsajh"
}

###

GET {{auth.jwt.non_refresh_token_HostAddress}}/weatherforecast
Authorization: Bearer 

###
